### ISSUE TITLE
is this framework supports mobile web browsers?

### ISSUE THREAD

**Issue by RollerIn** [WasiqB/coteafs-appium#167]
Hi Wasiq,
Hope you are doing good!!!
is this framework supports all mobile web browsers on iOS and android ?

browsers like chrome, Firefox, safari ? 

if not, can you suggest some good framework form you?

**Comment by mfaisalkhatri** [comment]
Hi, This Framework supports Chrome, Chromium and Safari browsers.
For more details please refer https://wasiqb.github.io/projects/appium/device-setting/

You will have to add the browser name in the following main section in the config and in the app section you need to set the app type to WEB. Using the `navigateTo` method in `deviceAction` class you can navigate to the url in the browser.

```
device: &default_device
  os: ANDROID
  type: REAL
  language: US
  browser: CHROME
  session_timeout: 120000

 devices:
  android:
    <<: *default_device
    name: emulator-5554
    version: 8.1
    automation: UIAUTOMATOR2
    type: SIMULATOR
      app:
        install_timeout: 60000
        type: WEB
```
